### ISSUE TITLE
Cause bug when have struct method

### ISSUE THREAD

**Issue by j796160836** [liip/sheriff#30] opened 2021-06-14 12:00 UTC
Hi, I found a bug when a structure having method.
For the example,

Find the `User` struct in sample code

```
type User struct {
	Username string   `json:"username" groups:"api"`
	Email    string   `json:"email"`
	Name     string   `json:"name" groups:"api"`
	Roles    []string `json:"roles" groups:"api"`
}
```

Add the following code below,

```
func (u User) String() string {
	return fmt.Sprintf("User<%s %s>", u.Username, u.Name)
}
```

It will brick the scoping, marshal all the stuff into json.

**Comment by mweibel** [comment] 2024-03-06 06:50
```go
func TestMarshal_User(t *testing.T) {
	u := &User{
		Username: "test",
		Email:    "foo@bar.org",
		Name:     "tester",
		Roles:    []string{"admin"},
	}
	v, err := Marshal(&Options{Groups: []string{"api"}}, u)
	assert.NoError(t, err)
	assert.Equal(t, map[string]interface {}{"name":"tester", "roles":[]interface {}{"admin"}, "username":"test"}, v)
}
```

This looks correct to me. Please clarify what the issue is or provide a PR. Until then, I close the issue.

**Closed by mweibel** 2024-03-06 06:50 UTC
